// codegen — emits role_permissions.go for this SDK from the
// permission-contract JSON file.
//
// Usage:
//   go run ./cmd/codegen <path-to-permissions.json> > role_permissions.go
//
// The permission-contract repo ships the canonical permissions.json.
// The CI pipeline fetches the contract at a pinned version, runs
// this codegen, and diffs the output against the committed
// role_permissions.go — drift fails the build.
//
// This binary is a thin wrapper around the emitter in the
// permission-contract repo (scripts/codegen-go.mjs). The Node
// emitter is the source of truth; this binary exists so `go run`
// works in a slim Go image (no Node required at SDK build time).
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"
)

// perm is the v1.3.0+ perm shape — a {name, scope} object.
type perm struct {
	Name  string `json:"name"`
	Scope string `json:"scope"`
}

type contract struct {
	Version     string `json:"version"`
	Services    []string `json:"services"`
	Roles       []string `json:"roles"`
	Permissions map[string][]perm `json:"permissions"`
	RolePerms   map[string]struct {
		Permissions []string `json:"permissions"`
	} `json:"role_permissions"`
}

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: codegen <path-to-permissions.json>")
		os.Exit(2)
	}
	path := os.Args[1]
	data, err := os.ReadFile(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read %s: %v\n", path, err)
		os.Exit(1)
	}
	var c contract
	if err := json.Unmarshal(data, &c); err != nil {
		fmt.Fprintf(os.Stderr, "parse %s: %v\n", path, err)
		os.Exit(1)
	}

	out, err := emit(c)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Print(out)
}

func emit(c contract) (string, error) {
	if c.Version == "" {
		return "", fmt.Errorf("contract: missing version")
	}
	if len(c.Roles) == 0 {
		return "", fmt.Errorf("contract: no roles")
	}

	// Flatten and bucket by scope. Iterate services in the contract's
	// declared order (c.Services) so the emitted tuples are deterministic —
	// Go map iteration over c.Permissions is randomized.
	var allPerms []string
	var selfPerms, platformPerms, projectPerms, dualPerms []string
	scopeOf := map[string]string{} // name → scope
	for _, svc := range c.Services {
		for _, p := range c.Permissions[svc] {
			allPerms = append(allPerms, p.Name)
			scopeOf[p.Name] = p.Scope
			switch p.Scope {
			case "self":
				selfPerms = append(selfPerms, p.Name)
			case "platform":
				platformPerms = append(platformPerms, p.Name)
			case "project":
				projectPerms = append(projectPerms, p.Name)
			case "platform/project":
				dualPerms = append(dualPerms, p.Name)
			}
		}
	}
	sort.Strings(allPerms) // const block — alphabetical for diff stability

	var b strings.Builder

	// Header
	fmt.Fprintf(&b, "// Code generated by permission-contract/codegen-go.mjs DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: permission-contract v%s\n", c.Version)
	fmt.Fprintf(&b, "// Generated at: %s\n", time.Now().UTC().Format("2006-01-02"))
	fmt.Fprintf(&b, "// Regenerate via: node scripts/codegen-go.mjs permissions.json > role_permissions.go\n")
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// The Permission type, PERM_SCOPE map, and ROLE_PERMISSIONS map are derived\n")
	fmt.Fprintf(&b, "// from the language-agnostic JSON contract. To change the platform's role →\n")
	fmt.Fprintf(&b, "// permission matrix, edit permissions.json in wazobiatech/permission-contract\n")
	fmt.Fprintf(&b, "// and re-run codegen — do not edit this file by hand.\n")
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// Permission naming convention: {service}:{resource}:{action}.\n")
	fmt.Fprintf(&b, "//   service  — one of: %s\n", strings.Join(c.Services, ", "))
	fmt.Fprintf(&b, "//   resource — domain noun (project, users, posts, members, ...)\n")
	fmt.Fprintf(&b, "//   action   — verb (view, write, delete, manage, ...)\n")
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// v1.3.0 perm scopes — the resolver uses PERM_SCOPE[perm] to gate which\n")
	fmt.Fprintf(&b, "// path (platform-user vs tenant-user) is valid for a given perm:\n")
	fmt.Fprintf(&b, "//   self              — universal, granted implicitly (no role needed)\n")
	fmt.Fprintf(&b, "//   platform          — granted via ROLE_PERMISSIONS (platform-user path);\n")
	fmt.Fprintf(&b, "//                       cannot be bundled into a TenantRole\n")
	fmt.Fprintf(&b, "//   project           — granted via TenantRole (tenant-user path);\n")
	fmt.Fprintf(&b, "//                       cannot appear in ROLE_PERMISSIONS\n")
	fmt.Fprintf(&b, "//   platform/project  — valid via either path (dual-scope).\n")
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// Package helios_permissions mirrors the TS / Python SDKs. Callers gate\n")
	fmt.Fprintf(&b, "// decisions on the returned []Permission; a perm not listed in this file is\n")
	fmt.Fprintf(&b, "// a typo and will fail to compile against the Permission type alias.\n")
	fmt.Fprintf(&b, "package helios_permissions\n\n")

	// Role
	fmt.Fprintf(&b, "// Role is the closed enum of platform roles. Mirrors the RoleType Prisma\n")
	fmt.Fprintf(&b, "// enum in Helios. New roles must be added to the contract's roles[] array\n")
	fmt.Fprintf(&b, "// and the codegen re-run.\n")
	fmt.Fprintf(&b, "type Role string\n\n")
	fmt.Fprintf(&b, "const (\n")
	for _, r := range c.Roles {
		fmt.Fprintf(&b, "\tRole%s Role = %q\n", pascalizeRole(r), r)
	}
	fmt.Fprintf(&b, ")\n\n")

	// Permission consts (alphabetical)
	fmt.Fprintf(&b, "// Permission is the closed string union of every permission in the platform.\n")
	fmt.Fprintf(&b, "// Compile-time guard: a perm not listed here is a typo.\n")
	fmt.Fprintf(&b, "type Permission string\n\n")
	fmt.Fprintf(&b, "const (\n")
	for _, p := range allPerms {
		fmt.Fprintf(&b, "\t%s Permission = %q\n", permConstName(p), p)
	}
	fmt.Fprintf(&b, ")\n\n")

	// PermScope
	fmt.Fprintf(&b, "// PermScope is the closed set of valid permission scopes. Mirrors the\n")
	fmt.Fprintf(&b, "// contract's scope enum.\n")
	fmt.Fprintf(&b, "type PermScope string\n\n")
	fmt.Fprintf(&b, "const (\n")
	fmt.Fprintf(&b, "\tScopeSelf              PermScope = \"self\"\n")
	fmt.Fprintf(&b, "\tScopePlatform          PermScope = \"platform\"\n")
	fmt.Fprintf(&b, "\tScopeProject           PermScope = \"project\"\n")
	fmt.Fprintf(&b, "\tScopePlatformProject   PermScope = \"platform/project\"\n")
	fmt.Fprintf(&b, ")\n\n")

	// Scope-partitioned tuples
	emitTuple := func(name string, items []string) {
		fmt.Fprintf(&b, "var %s = []Permission{\n", name)
		for _, p := range items {
			fmt.Fprintf(&b, "\t%s,\n", permConstName(p))
		}
		fmt.Fprintf(&b, "}\n\n")
	}
	fmt.Fprintf(&b, "// SELF_PERMISSIONS — universal perms granted implicitly to every\n")
	fmt.Fprintf(&b, "// authenticated user. Never appear in any ROLE_PERMISSIONS entry.\n")
	emitTuple("SELF_PERMISSIONS", selfPerms)
	fmt.Fprintf(&b, "// PLATFORM_PERMISSIONS — granted via ROLE_PERMISSIONS[role] (platform-user\n")
	fmt.Fprintf(&b, "// path). Cannot be bundled into a TenantRole.\n")
	emitTuple("PLATFORM_PERMISSIONS", platformPerms)
	fmt.Fprintf(&b, "// PROJECT_PERMISSIONS — granted via TenantRole (tenant-user path). Cannot\n")
	fmt.Fprintf(&b, "// appear in any ROLE_PERMISSIONS entry.\n")
	emitTuple("PROJECT_PERMISSIONS", projectPerms)
	fmt.Fprintf(&b, "// DUAL_PERMISSIONS — valid via either the platform-user path\n")
	fmt.Fprintf(&b, "// (ROLE_PERMISSIONS) or the tenant-user path (TenantRole bundle).\n")
	emitTuple("DUAL_PERMISSIONS", dualPerms)

	// PERM_SCOPE
	fmt.Fprintf(&b, "// PERM_SCOPE — perm → scope lookup, populated at module load. The two-track\n")
	fmt.Fprintf(&b, "// resolver in Helios checks PERM_SCOPE[perm] to decide which path\n")
	fmt.Fprintf(&b, "// (platform-user vs tenant-user) is valid for the perm.\n")
	fmt.Fprintf(&b, "var PERM_SCOPE = map[Permission]PermScope{\n")
	for _, p := range selfPerms {
		fmt.Fprintf(&b, "\t%s: ScopeSelf,\n", permConstName(p))
	}
	for _, p := range platformPerms {
		fmt.Fprintf(&b, "\t%s: ScopePlatform,\n", permConstName(p))
	}
	for _, p := range projectPerms {
		fmt.Fprintf(&b, "\t%s: ScopeProject,\n", permConstName(p))
	}
	for _, p := range dualPerms {
		fmt.Fprintf(&b, "\t%s: ScopePlatformProject,\n", permConstName(p))
	}
	fmt.Fprintf(&b, "}\n\n")

	// Roles slice
	fmt.Fprintf(&b, "// Roles lists every role in the platform. Same order as the contract's\n")
	fmt.Fprintf(&b, "// roles[] array.\n")
	fmt.Fprintf(&b, "var Roles = []Role{\n")
	for _, r := range c.Roles {
		fmt.Fprintf(&b, "\tRole%s,\n", pascalizeRole(r))
	}
	fmt.Fprintf(&b, "}\n\n")

	// IsValidPermission
	fmt.Fprintf(&b, "// IsValidPermission reports whether p is a known permission string.\n")
	fmt.Fprintf(&b, "func IsValidPermission(p Permission) bool {\n")
	fmt.Fprintf(&b, "\t_, ok := PERM_SCOPE[p]\n")
	fmt.Fprintf(&b, "\treturn ok\n")
	fmt.Fprintf(&b, "}\n\n")

	// IsValidRole
	fmt.Fprintf(&b, "// IsValidRole reports whether r is a known role string.\n")
	fmt.Fprintf(&b, "func IsValidRole(r Role) bool {\n")
	fmt.Fprintf(&b, "\tswitch r {\n")
	for _, r := range c.Roles {
		fmt.Fprintf(&b, "\tcase Role%s:\n", pascalizeRole(r))
		fmt.Fprintf(&b, "\t\treturn true\n")
	}
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "\treturn false\n")
	fmt.Fprintf(&b, "}\n\n")

	// IsSelfScope
	fmt.Fprintf(&b, "// IsSelfScope reports whether perm has scope \"self\" (universal — granted\n")
	fmt.Fprintf(&b, "// without any role lookup). Used by the resolver's Step 1.\n")
	fmt.Fprintf(&b, "func IsSelfScope(perm Permission) bool {\n")
	fmt.Fprintf(&b, "\treturn PERM_SCOPE[perm] == ScopeSelf\n")
	fmt.Fprintf(&b, "}\n\n")

	// IsPlatformGrantable
	fmt.Fprintf(&b, "// IsPlatformGrantable reports whether perm is grantable via the\n")
	fmt.Fprintf(&b, "// platform-user path (scope is \"platform\" or \"platform/project\").\n")
	fmt.Fprintf(&b, "func IsPlatformGrantable(perm Permission) bool {\n")
	fmt.Fprintf(&b, "\ts := PERM_SCOPE[perm]\n")
	fmt.Fprintf(&b, "\treturn s == ScopePlatform || s == ScopePlatformProject\n")
	fmt.Fprintf(&b, "}\n\n")

	// IsTenantGrantable
	fmt.Fprintf(&b, "// IsTenantGrantable reports whether perm is grantable via the tenant-user\n")
	fmt.Fprintf(&b, "// path. Scope \"project\" and \"platform/project\" are grantable; any perm NOT\n")
	fmt.Fprintf(&b, "// in PERM_SCOPE is treated as tenant-defined and therefore grantable via\n")
	fmt.Fprintf(&b, "// TenantRole.\n")
	fmt.Fprintf(&b, "func IsTenantGrantable(perm string) bool {\n")
	fmt.Fprintf(&b, "\ts, ok := PERM_SCOPE[Permission(perm)]\n")
	fmt.Fprintf(&b, "\tif !ok {\n")
	fmt.Fprintf(&b, "\t\treturn true\n")
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "\treturn s == ScopeProject || s == ScopePlatformProject\n")
	fmt.Fprintf(&b, "}\n\n")

	// ROLE_PERMISSIONS
	fmt.Fprintf(&b, "// ROLE_PERMISSIONS is the canonical role → permission map. Every role lists\n")
	fmt.Fprintf(&b, "// its permissions explicitly — there is no inheritance. The contract\n")
	fmt.Fprintf(&b, "// validator (scripts/validate.mjs) enforces:\n")
	fmt.Fprintf(&b, "//   - helios:tenant:switch:self is present as a self-scope perm (universal).\n")
	fmt.Fprintf(&b, "//   - helios:tenant:transfer is OWNER-only (platform scope).\n")
	fmt.Fprintf(&b, "//   - Every role has >= 1 permission.\n")
	fmt.Fprintf(&b, "//   - No role references a perm outside the vocabulary.\n")
	fmt.Fprintf(&b, "//   - No self or project perms in any role.\n")
	fmt.Fprintf(&b, "var ROLE_PERMISSIONS = map[Role][]Permission{\n")
	for _, r := range c.Roles {
		perms := append([]string(nil), c.RolePerms[r].Permissions...)
		sort.Strings(perms)
		fmt.Fprintf(&b, "\tRole%s: {\n", pascalizeRole(r))
		for _, p := range perms {
			fmt.Fprintf(&b, "\t\t%s,\n", permConstName(p))
		}
		fmt.Fprintf(&b, "\t},\n")
	}
	fmt.Fprintf(&b, "}\n\n")

	// ResolvePermissions
	fmt.Fprintf(&b, "// ResolvePermissions returns ROLE_PERMISSIONS[role]. Returns an empty slice\n")
	fmt.Fprintf(&b, "// for unknown roles (defensive — caller code should be using the typed\n")
	fmt.Fprintf(&b, "// Role constants, but a runtime string from an untrusted source might not be).\n")
	fmt.Fprintf(&b, "func ResolvePermissions(role Role) []Permission {\n")
	fmt.Fprintf(&b, "\tif perms, ok := ROLE_PERMISSIONS[role]; ok {\n")
	fmt.Fprintf(&b, "\t\treturn perms\n")
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "\treturn []Permission{}\n")
	fmt.Fprintf(&b, "}\n\n")

	// RoleHasPermission
	fmt.Fprintf(&b, "// RoleHasPermission reports whether role is granted perm. Both args must be\n")
	fmt.Fprintf(&b, "// typed constants for the call to compile — a typo in a perm string will\n")
	fmt.Fprintf(&b, "// not satisfy the Permission type alias.\n")
	fmt.Fprintf(&b, "func RoleHasPermission(role Role, perm Permission) bool {\n")
	fmt.Fprintf(&b, "\tfor _, p := range ROLE_PERMISSIONS[role] {\n")
	fmt.Fprintf(&b, "\t\tif p == perm {\n")
	fmt.Fprintf(&b, "\t\treturn true\n")
	fmt.Fprintf(&b, "\t\t}\n")
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "\treturn false\n")
	fmt.Fprintf(&b, "}\n")
	fmt.Fprintf(&b, "\n")

	return b.String(), nil
}

// pascalizeRole turns OWNER → Owner, ADMIN → Admin, etc.
// (capitalize first letter, lowercase the rest — for role constants).
func pascalizeRole(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + strings.ToLower(s[1:])
}

// pascalizeSegment capitalizes the first letter only, preserving the rest
// of the segment verbatim (per the Node emitter's `charAt(0).toUpperCase()
// + slice(1)`). E.g. "api_keys" → "Api_keys", "USER" → "USER".
func pascalizeSegment(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// permConstName turns "athens:project:view" → "AthensProjectView".
// "mercury:api_keys:manage" → "MercuryApi_keysManage".
func permConstName(p string) string {
	parts := strings.Split(p, ":")
	for i, seg := range parts {
		parts[i] = pascalizeSegment(seg)
	}
	return "Permission" + strings.Join(parts, "")
}