// codegen — emits role_permissions.go for this SDK from the
// permission-contract JSON file.
//
// Usage:
//   go run ./cmd/codegen <path-to-permissions.json> > role_permissions.go
//
// The permission-contract repo ships the canonical permissions.json.
// The CI pipeline fetches the contract at a pinned version, runs
// this codegen, and diffs the output against the committed
// role_permissions.go — drift fails the build.
//
// This binary is a thin wrapper around the emitter in the
// permission-contract repo (scripts/codegen-go.mjs). The Node
// emitter is the source of truth; this binary exists so `go run`
// works in a slim Go image (no Node required at SDK build time).
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"
)

type contract struct {
	Version    string              `json:"version"`
	Services   []string            `json:"services"`
	Roles      []string            `json:"roles"`
	Permissions map[string][]string `json:"permissions"`
	RolePerms  map[string]struct {
		Permissions []string `json:"permissions"`
	} `json:"role_permissions"`
}

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: codegen <path-to-permissions.json>")
		os.Exit(2)
	}
	path := os.Args[1]
	data, err := os.ReadFile(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read %s: %v\n", path, err)
		os.Exit(1)
	}
	var c contract
	if err := json.Unmarshal(data, &c); err != nil {
		fmt.Fprintf(os.Stderr, "parse %s: %v\n", path, err)
		os.Exit(1)
	}

	out, err := emit(c)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Print(out)
}

func emit(c contract) (string, error) {
	if c.Version == "" {
		return "", fmt.Errorf("contract: missing version")
	}
	if len(c.Roles) == 0 {
		return "", fmt.Errorf("contract: no roles")
	}
	var b strings.Builder

	// Header
	fmt.Fprintf(&b, "// Code generated by helios-permissions-go/cmd/codegen DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: permission-contract v%s\n", c.Version)
	fmt.Fprintf(&b, "// Generated at: %s\n", time.Now().UTC().Format("2006-01-02"))
	fmt.Fprintf(&b, "// Regenerate via: go run ./cmd/codegen <path-to-permissions.json> > role_permissions.go\n")
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// The Permission type and ROLE_PERMISSIONS map are derived from the\n")
	fmt.Fprintf(&b, "// language-agnostic JSON contract. To change the platform's role → permission\n")
	fmt.Fprintf(&b, "// matrix, edit permissions.json in wazobiatech/permission-contract and re-run\n")
	fmt.Fprintf(&b, "// codegen — do not edit this file by hand.\n")
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// Permission naming convention: {service}:{resource}:{action}.\n")
	fmt.Fprintf(&b, "//   service  — one of: %s\n", strings.Join(c.Services, ", "))
	fmt.Fprintf(&b, "//   resource — domain noun (project, users, posts, members, ...)\n")
	fmt.Fprintf(&b, "//   action   — verb (view, write, delete, manage, ...)\n")
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// Package helios_permissions mirrors the TS / Python SDKs. Callers gate\n")
	fmt.Fprintf(&b, "// decisions on the returned []Permission; a perm not listed in this file is\n")
	fmt.Fprintf(&b, "// a typo and will fail to compile against the Permission type alias.\n")
	fmt.Fprintf(&b, "package helios_permissions\n\n")

	// Role
	fmt.Fprintf(&b, "// Role is the closed enum of platform roles. Mirrors the RoleType Prisma\n")
	fmt.Fprintf(&b, "// enum in Helios. New roles must be added to the contract's roles[] array\n")
	fmt.Fprintf(&b, "// and the codegen re-run.\n")
	fmt.Fprintf(&b, "type Role string\n\n")
	fmt.Fprintf(&b, "const (\n")
	for _, r := range c.Roles {
		fmt.Fprintf(&b, "\tRole%s Role = %q\n", pascalize(r), r)
	}
	fmt.Fprintf(&b, ")\n\n")

	// Permission consts (alphabetical).
	var allPerms []string
	for _, ps := range c.Permissions {
		allPerms = append(allPerms, ps...)
	}
	sort.Strings(allPerms)

	fmt.Fprintf(&b, "// Permission is the closed string union of every permission in the platform.\n")
	fmt.Fprintf(&b, "// Compile-time guard: a perm not listed here is a typo.\n")
	fmt.Fprintf(&b, "type Permission string\n\n")
	fmt.Fprintf(&b, "const (\n")
	for _, p := range allPerms {
		fmt.Fprintf(&b, "\tPermission%s Permission = %q\n", permConstName(p), p)
	}
	fmt.Fprintf(&b, ")\n\n")

	// Roles slice
	fmt.Fprintf(&b, "// Roles lists every role in the platform. Same order as the contract's\n")
	fmt.Fprintf(&b, "// roles[] array.\n")
	fmt.Fprintf(&b, "var Roles = []Role{\n")
	for _, r := range c.Roles {
		fmt.Fprintf(&b, "\tRole%s,\n", pascalize(r))
	}
	fmt.Fprintf(&b, "}\n\n")

	// IsValidPermission
	fmt.Fprintf(&b, "// IsValidPermission reports whether p is a known permission string.\n")
	fmt.Fprintf(&b, "func IsValidPermission(p Permission) bool {\n")
	fmt.Fprintf(&b, "\tswitch p {\n")
	for _, p := range allPerms {
		fmt.Fprintf(&b, "\tcase Permission%s:\n", permConstName(p))
		fmt.Fprintf(&b, "\t\treturn true\n")
	}
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "\treturn false\n")
	fmt.Fprintf(&b, "}\n\n")

	// IsValidRole
	fmt.Fprintf(&b, "// IsValidRole reports whether r is a known role string.\n")
	fmt.Fprintf(&b, "func IsValidRole(r Role) bool {\n")
	fmt.Fprintf(&b, "\tswitch r {\n")
	for _, r := range c.Roles {
		fmt.Fprintf(&b, "\tcase Role%s:\n", pascalize(r))
		fmt.Fprintf(&b, "\t\treturn true\n")
	}
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "\treturn false\n")
	fmt.Fprintf(&b, "}\n\n")

	// ROLE_PERMISSIONS
	fmt.Fprintf(&b, "// ROLE_PERMISSIONS is the canonical role → permission map. Every role lists\n")
	fmt.Fprintf(&b, "// its permissions explicitly — there is no inheritance. The contract\n")
	fmt.Fprintf(&b, "// validator (scripts/validate.mjs) enforces:\n")
	fmt.Fprintf(&b, "//   - helios:tenant:switch is present in every role (universal perm).\n")
	fmt.Fprintf(&b, "//   - helios:tenant:transfer is present only in OWNER (ZIN-4714).\n")
	fmt.Fprintf(&b, "//   - Every role has >= 1 permission.\n")
	fmt.Fprintf(&b, "//   - No role references a perm outside the vocabulary.\n")
	fmt.Fprintf(&b, "var ROLE_PERMISSIONS = map[Role][]Permission{\n")
	for _, r := range c.Roles {
		perms := append([]string(nil), c.RolePerms[r].Permissions...)
		sort.Strings(perms)
		fmt.Fprintf(&b, "\tRole%s: {\n", pascalize(r))
		for _, p := range perms {
			fmt.Fprintf(&b, "\t\tPermission%s,\n", permConstName(p))
		}
		fmt.Fprintf(&b, "\t},\n")
	}
	fmt.Fprintf(&b, "}\n\n")

	// ResolvePermissions
	fmt.Fprintf(&b, "// ResolvePermissions returns the permission set for role, or an empty slice\n")
	fmt.Fprintf(&b, "// for an unknown role. Defensive copy: callers may mutate the returned slice.\n")
	fmt.Fprintf(&b, "func ResolvePermissions(role Role) []Permission {\n")
	fmt.Fprintf(&b, "\tperms, ok := ROLE_PERMISSIONS[role]\n")
	fmt.Fprintf(&b, "\tif !ok {\n")
	fmt.Fprintf(&b, "\t\treturn []Permission{}\n")
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "\tout := make([]Permission, len(perms))\n")
	fmt.Fprintf(&b, "\tcopy(out, perms)\n")
	fmt.Fprintf(&b, "\treturn out\n")
	fmt.Fprintf(&b, "}\n\n")

	// RoleHasPermission
	fmt.Fprintf(&b, "// RoleHasPermission reports whether role is granted perm.\n")
	fmt.Fprintf(&b, "func RoleHasPermission(role Role, perm Permission) bool {\n")
	fmt.Fprintf(&b, "\tfor _, p := range ROLE_PERMISSIONS[role] {\n")
	fmt.Fprintf(&b, "\t\tif p == perm {\n")
	fmt.Fprintf(&b, "\t\t\treturn true\n")
	fmt.Fprintf(&b, "\t\t}\n")
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "\treturn false\n")
	fmt.Fprintf(&b, "}\n")

	return b.String(), nil
}

// pascalize turns OWNER → Owner, ADMIN → Admin, etc.
func pascalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + strings.ToLower(s[1:])
}

// permConstName turns "athens:project:view" → "AthensProjectView".
// "mercury:api-keys:manage" → "MercuryApi_keysManage" (preserves the
// raw segment between underscores and the next colon).
func permConstName(p string) string {
	parts := strings.Split(p, ":")
	for i, seg := range parts {
		parts[i] = pascalize(seg)
	}
	return strings.Join(parts, "")
}
